version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ufv-foundit-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    networks:
      - ufv-foundit-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ufv-foundit-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    environment:
      # En el futuro puedes leer esto desde import.meta.env.VITE_API_BASE_URL
      - VITE_API_BASE_URL=http://backend:4000
    networks:
      - ufv-foundit-net

networks:
  ufv-foundit-net:
    driver: bridge
